name: env_govlatinamerica2
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - tinydb
  - beautifulsoup4
  - yattag
  - python-dotenv
  - lxml
  - pip
  - requests
  - waybackpy
  
  
prefix: ~/.conda/envs/env_govlatinamerica
